package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class MainPageTests extends TestBase {
    @Test
    @Description("Test search work by site")
    @DisplayName("Send request and check result of searching")
    public void searchingTest(String request) {
        step("open https://www.luxoft.com/", () -> {
            open("https://www.luxoft.com/");
        });

        step("Click on icon of seacrhing", () -> {
            $(".icomoon-search").shouldBe(visible);
            $(".icomoon-search").click();
        });

        step("Send search request", () -> {
            $("#query-search").setValue(request);
            $("#test").click();
        });
        step("Send search request", () -> {
            $("#query-search").setValue(request);
            $("#test").click();
        });
        step("Response contains query string", () -> {
            $(".search-results__items .search-results__item p").shouldHave(text(request));
        });

    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.luxoft.com/'", () ->
            open("https://www.luxoft.com/"));

        step("Page title should have text 'Luxoft | Digital Strategy, Consulting and Engineering at Scale'", () -> {
            String expectedTitle = "Luxoft | Digital Strategy, Consulting and Engineering at Scale";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.luxoft.com/'", () ->
            open("https://www.luxoft.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}
